### ISSUE TITLE
APK stops working upon rebooting the Quest.

### ISSUE THREAD

**Issue by therf311** [madmagic007/Oculus-Quest-Presence#11]
Hi there, I just finished the setup of the application, but when I got to the step where you restart the Quest, I got an error message saying "Oqrpc has stopped working", which I confirmed with the Validate tool in the PC settings. Is there a fix for this, or did I do something wrong somewhere? Thanks.

**Comment by madmagic007** [comment]
this is an issue I'm aware of and should be fixed somewhere next week. to solve this for now you have to go to the releases section, download the zip from the 2.3.0 release and use the apk and installer from there, of you use a Mac let me know because you need a different jar than the one found in the txt file

**Comment by therf311** [comment]
Thanks, I'll do this when I get the time.

**Comment by madmagic007** [comment]
i thought i would give an update on the issue. the issue itself is quite easy but i cant work on a fix untill next week, for now i just rerolled the old version and pushed it to github. 
anyone that still has this issue, head over to the releases tab and download the zip from 2.3.0
