### ISSUE TITLE
I have found malware in this.

### ISSUE THREAD

**Issue by Yeetzys** [madmagic007/Oculus-Quest-Presence#46]
Theres a trojan in this. do not install. the trojans name was something like: "Trojan/Win32".
If you dont believe me, add me on discord @YeetzysOnPC#6502

**Comment by RyanTheTide** [comment]
Jesus the amount of these comments I see honestly just baffles me especially here on GitHub, not that I believe your competent enough to understand this concept, but this software is what’s referred to as, in the community, ‘Open Source’. Do you know what that means? Because if you did you’d comb over the code which is public (shocking I know) & then you’d compile the application yourself.

Or if you are new to code and have no clue what your doing, give this repository to a friend of yours and ask them where this Trojan is in the code. Or another idea trust the people you watch daily, see who uses this program and then decide if it’s trustworthy.

- RyanTheTide
- aka Furious about people who don’t get the concept of open source.

**Comment by madmagic007** [comment]
I have no clue why windows says that to some people, I assume it's related with the auto updating. but exactly like Ryan said, you can look at the code yourself and see that there's no virus in it
