### ISSUE TITLE
Discord shows online when headset is off.

### ISSUE THREAD

**Issue by ethsanders** [madmagic007/Oculus-Quest-Presence#9]
Discord shows "Playing Oculus Quest | In Oculus Home" even when my headset has been put to sleep. This also happens even when I reboot the program without turning the headset on.
![Annotation 2020-04-09 180423](https://user-images.githubusercontent.com/19353344/78947981-8f83a180-7a8c-11ea-9758-be4a17a2a345.png)

**Comment by ethsanders** [comment]
Did a little more research, and the issue is that the APK is still running on the device when it is on sleep mode.

**Comment by madmagic007** [comment]
this happens because as long as the computer receives a response from your quest, it will show the presence. I can make it test if the device is in sleep mode and then not respond. but that would cause some issues because then I have to constantly check when the device isn't in sleep mode anymore to get the presence to start. I can just make it stop, but then you would have to manually start the presence after.
